version: 0.2

env:
  variables:
    AWS_REGION_NAME: ap-northeast-1
    ECR_REPOSITORY_NAME: iacontainer-ecr

phases:
  pre_build:
    commands:
    - $(aws ecr get-login --region $AWS_REGION_NAME --no-include-email)
    - REPO=$(aws ecr describe-repositories --repository-names example --output text --query "repositories[0].repositoryUri")
    - IMAGE=$REPO:latest
  build:
    commands:
    - docker build -t $IMAGE .
    - docker push $IMAGE
  post_build:
    commands:
    - printf '[{"name":"iacontainer-ecr","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json